name: Multi-Environment Deployment with Notifications
 
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - prod
  workflow_dispatch:
 
permissions:
  contents: write
  id-token: write
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
 
      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json
 
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci
 
      # Step 4: Run tests (only for dev branch)
      - name: Run tests
        if: github.ref_name == 'dev'
        run: npm test
 
      # Step 5: Build the app
      - name: Build the app
        run: npm run build --verbose
 
      # Step 6: List dist directory for debugging
      - name: List dist directory
        run: ls -alh /dist || echo "Dist directory not found"
 
      # Step 7: Deploy to Netlify (dev branch)
      - name: Deploy to Netlify (dev)
        if: github.ref == 'refs/heads/dev'
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./dist
          production-deploy: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}
          HOMEPAGE_URL: ${{ secrets.HOMEPAGE_URL }}
 
            # Step 8: Send email for dev deploy
      - name: Send email for dev deploy
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}  # Your Gmail address
          password: ${{ secrets.SMTP_PASSWORD }}  # App password
          subject: "Code Deployed to Dev Environment"
          body: "The latest code has been successfully deployed to the dev environment. Visit the site at ${{ secrets.HOMEPAGE_URL }}."
          to: "srikarvanaparthy21@gmail.com"
          from: "srikarvanaparthy@gmail.com"

 
  create-pull-request:
    name: Create Pull Request for Dev to Prod
    runs-on: ubuntu-latest
    needs: build-and-deploy  # This ensures the PR is created after the build-and-deploy job finishes successfully
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge dev into prod"
          branch: dev
          base: prod
          title: "Pull Request: Merge Dev into Prod"
          body: "This pull request is for merging the changes from the dev branch to the prod branch."
          auto-merge: false  # Ensure the pull request is not merged automatically
          

 
  deploy-to-netlify-prod:
    name: Deploy to Netlify (Prod)
    runs-on: ubuntu-latest
    needs: create-pull-request  # This ensures the deploy happens after the PR creation
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
 
      # Step 2: Install dependencies
      - name: Install dependencies
        run: npm ci
 
      # Step 3: Build the app
      - name: Build the app
        run: npm run build --verbose
 
      # Step 4: List dist directory for debugging
      - name: List dist directory
        run: ls -alh /build || echo "Dist directory not found"
 
      # Step 5: Deploy to Netlify (prod branch)
      - name: Deploy to Netlify (Prod)
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./dist
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PROD_SITE_ID }}
          HOMEPAGE_URL: ${{ secrets.PROD_HOMEPAGE_URL }}
 
      # Step 8: Send email for dev deploy
      - name: Send email for dev deploy
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}  # Your Gmail address
          password: ${{ secrets.SMTP_PASSWORD }}  # App password
          subject: "Code Deployed to Dev Environment"
          body: "The latest code has been successfully deployed to the dev environment. Visit the site at ${{ secrets.HOMEPAGE_URL }}."
          to: "srikarvanaparthy21@gmail.com"
          from: "srikarvanaparthy@gmail.com"

 