name: CI/CD Pipeline with Auto-Promotion

on:
  push:
    branches:
      - dev
      - prod

jobs:
  build-test:
    name: Build and Test React App
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'  # Only run on the 'dev' branch

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test -- --watchAll=false

      - name: Build App
        run: npm run build

  auto-merge-to-prod:
    name: Auto-Merge to Prod
    runs-on: ubuntu-latest
    needs: build-test
    if: success() && github.ref == 'refs/heads/dev'  # Only run on 'dev' branch after build-test success

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git User
        run: |
          git config --global user.name "SrikarVanaparthy"
          git config --global user.email "svanaparthy@anergroup.com"

      - name: Merge Dev into Prod
        run: |
          git fetch origin
          git checkout prod
          git merge dev --allow-unrelated-histories
          git push origin prod

  deploy:
    name: Deploy React App to AWS
    runs-on: ubuntu-latest
    needs: auto-merge-to-prod  # Only run after auto-merge-to-prod is successful
    if: github.ref == 'refs/heads/dev'  # Only run on 'prod' branch

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync to S3
        run: aws s3 sync ./build s3://srikar-aws --delete
