name: Multi-Environment Deployment with Pull Requests and Email Notifications
on:
  push:
    branches:
      - dev
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run tests (only for dev branch)
      - name: Run tests
        if: github.ref_name == 'dev'
        run: npm test

      # Step 5: Build the app
      - name: Build the app
        run: npm run build --verbose

      # Step 6: List dist directory for debugging
      - name: List dist directory
        run: ls -alh ./dist || echo "Dist directory not found"

      # Step 7: Deploy to Netlify (dev)
      - name: Deploy to Netlify (dev)
        if: github.ref == 'refs/heads/dev'
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./dist
          production-deploy: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_TEST_SITE_ID }}
          HOMEPAGE_URL: ${{ secrets.HOMEPAGE_URL }}

  create-pull-request:
    name: Create Pull Request from Dev to Prod
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: success() && github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: prod
          head: dev
          title: "Merge Dev into Prod"
          body: |
            Automated pull request to merge changes from `dev` to `prod`.
            Please review and approve the changes for production deployment.
          labels: "automated"
          draft: false

  deploy-to-netlify-prod:
    name: Deploy to Netlify (Prod)
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.base_ref == 'prod'
    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 3: Build the app
      - name: Build the app
        run: npm run build --verbose

      # Step 4: List dist directory for debugging
      - name: List dist directory
        run: ls -alh ./dist || echo "Dist directory not found"

      # Step 5: Deploy to Netlify (Prod)
      - name: Deploy to Netlify (Prod)
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./dist
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PROD_SITE_ID }}
          HOMEPAGE_URL: ${{ secrets.PROD_HOMEPAGE_URL }}

      # Step 6: Send email notification for prod deployment
      - name: Send email notification for prod deployment
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.yourmailserver.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          to: recipient@example.com
          from: sender@example.com
          subject: "Deployment to Prod Completed"
          body: "The deployment to the Prod environment is complete."
